const express = require('express');
const router = express.Router();
var suggestion = {
    "Name of the Place ": [
        "Terraced Garden",
        "Garden of Silence",
        "Topiary Park",
        "Chandigarh Botanical Garden ",
        "International Dolls Museum",
        "Government Museum and Art Gallery",
        "Fun City",
        "Le Corbusier Centre",
        "Nek Chand Rock Garden of Chandigarh",
        "Leisure Valley",
        "Sukhana Lake Park",
        "Zakir Hussain Rose Garden",
        "Tank Monument",
        "Open Hand Monument",
        "Bougainvillea Park",
        "Dhanas Lake",
        "Patiala Ki Rao Reserved Forest",
        "Sukhna Wildlife Sanctuary",
        "Kansal Forest Rest House",
        "Chandigarh Architecture Museum",
        "Hibiscus Garden",
        "Butterfly Park ",
        "Cactus Garden ",
        "M.C. Zoological Park, Chhat Bir Zoo, Zirakpur ",
        "Fateh Burj, Chappar Chiri",
        "Eiffel Tower Replica ",
        "Children Traffic Park ",
        "Rose Garden",
        "Shanti Kunj Park ",
        "Yadavindra Gardens, Pinjore ",
        "Peacock Park ",
        "Bird Sanctuary "
    ],
    "Ratings": [
        4.4,
        4.5,
        4.2,
        4.4,
        4.1,
        4.4,
        4.2,
        4.4,
        4.5,
        4.4,
        4.6,
        4.4,
        4.3,
        4.5,
        4.4,
        4.5,
        4.1,
        4.4,
        4.5,
        4.5,
        4.4,
        4.1,
        4.4,
        4.3,
        4.4,
        4.1,
        4.1,
        4.4,
        4.4,
        4.3,
        4.2,
        4.2
    ],
    "Address": [
        "Sector 33B, Sector 33, Chandigarh, 160020",
        "5, Lake Walking Way, Kishangarh, Chandigarh, Punjab 160101",
        "Sub. City Center, Sector 35A, Chandigarh, 160035",
        "Sarangpur, Chandigarh, 160014",
        "Bal Bhawan, Udyog Path, Sector 23B, Chandigarh, 160023",
        "#502 sector, 10C, Chandigarh, 160011",
        "Elante Mall Patio, Purv Marg, Phase 1, Ram Darbar, Chandigarh, 160002",
        "Sector 19B Old Architect Building, Madhya Marg, Chandigarh, Punjab 160019",
        "Uttar Marg, Rock Garden of Chandigarh, Sector 1, Chandigarh, 160001",
        "10B, Sector 10B, Chandigarh, 160011",
        "Sector 6, Chandigarh, 160019",
        "Jan Marg, 16B, Sector 16, Chandigarh, 160016",
        "10C, Sector 10, Chandigarh, 160011",
        "31, Uttar Marg, Capitol Complex, Sector 1, Chandigarh, 160001",
        "3B, Sector 3, Chandigarh, 160001",
        "Dhanas Main Rd, Dhanas, Chandigarh, 160014",
        "3288, HBC, Dhanas, Chandigarh, 160014",
        "North-East Of Sukhna Lake, Chandigarh, India",
        "Unnamed Rd, Chandigarh, Kansal, 133301",
        "Museum and Art Gallery, Sector 10, Chandigarh, 160011",
        "Hibiscus Garden Rd, 36A, Sector 36, Chandigarh, 160036",
        "Sector 26, Chandigarh, 160019",
        "Panchkula Urban Estate, Sector 5, Panchkula, Haryana 134108",
        "Chattbir Zoo Rd, Chhat, Punjab 140603",
        "Chappar Chiri, Sector 93, Sahibzada Ajit Singh Nagar, Punjab 140307",
        "Leisure Valley, 10C, Sector 10C, Chandigarh, 160011",
        "Udyan Path, 23A, Sector 23, Chandigarh, 160023",
        "Phase 3B-1, Sector 60, Sahibzada Ajit Singh Nagar, Chandigarh 160059",
        "16C, Sector 16, Chandigarh, 160015",
        "Ambala, Kalka - Shimla Rd, Pinjore, Haryana 134102",
        "39A, Sector 39, Chandigarh, 160036",
        "279, Ward Number IV, Himalaya Marg, Sector 21A, Sector 21B, Sector 21, Chandigarh 160022"
    ],
    "Type of Place": [
        "Garden",
        "Tourist Attraction",
        "Tourist Attraction",
        "Tourist Attraction",
        "Children's Museum",
        "Art Museum",
        "Children's amusement center",
        "History Museum",
        "Museum",
        "Park",
        "Tourist Attraction",
        "Garden",
        "Monument",
        "Monument",
        "Park",
        "Tourist Attraction",
        "Nature Preserve",
        "Nature Preserve",
        "Tourist Attraction",
        "Museum",
        "Garden",
        "Park",
        "Garden",
        "Zoo",
        "Tourist Attraction",
        "Garden",
        "Park",
        "Park",
        "Park",
        "Garden",
        "Park",
        "National Park"
    ],
    "Opening Time": [
        "5:30 AM",
        "6:00 AM",
        "Open 24hrs",
        "Open 24hrs",
        "10:00",
        "10:00 AM",
        "11:00 AM",
        "10:00 AM",
        "9:00 AM",
        "Open 24hrs",
        "4:00 AM",
        "6:00 AM",
        "Open 24hrs",
        "9:00 AM",
        "Open 24hrs",
        "Open 24hrs",
        "10:00 AM",
        "9:00 AM",
        "9:00 AM",
        "10:00 AM",
        "Open 24hrs",
        "8:30 AM",
        "8:00 AM",
        "9:30 AM",
        "10:00 AM",
        "Open 24hrs",
        "9:00 AM",
        "6:00 AM",
        "Open 24hrs",
        "7:00 AM",
        "8:00 AM",
        "5:00 AM"
    ],
    "Closing Time": [
        "9:00 PM",
        "10:00 PM",
        "Open 24hrs",
        "Open 24hrs",
        "4:30 PM",
        "4:30 PM",
        "10:00 PM",
        "5:00 PM",
        "8:00 PM",
        "Open 24hrs",
        "10:00 PM",
        "10:00 PM",
        "Open 24hrs",
        "8:00 PM",
        "Open 24hrs",
        "Open 24hrs",
        "8:00 PM",
        "9:00 PM",
        "5:00 PM",
        "8:00 PM",
        "Open 24hrs",
        "5:00 PM",
        "6:00 PM",
        "4:30 PM",
        "7:00 PM",
        "Open 24hrs",
        "9:00 PM",
        "8:00 PM",
        "Open 24hrs",
        "9:30 PM",
        "5:00 PM",
        "8:15 PM"
    ],
    "Unnamed: 6": [
        null,
        null,
        null,
        null,
        "Monday Closed",
        "Monday Closed",
        "Sunday Monday Closing Time 7:30 PM",
        null,
        "Sunday Closing Time 3:45 PM",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ]
};
module.exports = suggestion;